name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Check if Shopify API Password is set
        run: |
          if [ -z "${{ secrets.SHOPIFY_PASSWORD }}" ]; then
            echo "SHOPIFY_PASSWORD is NOT set!"
          else
            echo "SHOPIFY_PASSWORD is set!"
          fi

      - name: Check if Shopify Store URL is set
        run: |
          if [ -z "${{ secrets.SHOPIFY_STORE_URL }}" ]; then
            echo "SHOPIFY_STORE_URL is NOT set!"
          else
            echo "SHOPIFY_STORE_URL is set!"
          fi

      - name: Set environment variables
        run: |
          echo "SHOPIFY_PASSWORD=${{ secrets.SHOPIFY_PASSWORD }}" >> $GITHUB_ENV
          echo "SHOPIFY_STORE_URL=${{ secrets.SHOPIFY_STORE_URL }}" >> $GITHUB_ENV
          echo "SHOPIFY_THEME_ID=${{ secrets.SHOPIFY_THEME_ID }}" >> $GITHUB_ENV
          echo "THEME_PATH=${{ secrets.THEME_PATH }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "SHOPIFY_PASSWORD: $SHOPIFY_PASSWORD"
          echo "SHOPIFY_STORE_URL: $SHOPIFY_STORE_URL"
          echo "SHOPIFY_THEME_ID: $SHOPIFY_THEME_ID"
          echo "THEME_PATH: $THEME_PATH"

      - name: Deploy Theme to Shopify
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          THEME_PATH: ${{ secrets.THEME_PATH }}
        run: |
          echo "Deploying Theme to Shopify..."
          shopify theme push $THEME_PATH --store $SHOPIFY_STORE_URL --password $SHOPIFY_PASSWORD --theme $SHOPIFY_THEME_ID
