name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Authenticate with Shopify CLI
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_API_PASSWORD }}  # Use API password stored in GitHub Secrets
        run: |
          # Authenticate Shopify CLI with API password for non-interactive login
          shopify login --store app-development-test729.myshopify.com --password ${{ secrets.SHOPIFY_API_PASSWORD }}

      - name: Deploy Theme
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_API_PASSWORD }}  # Ensure token is passed for the deploy step
        run: shopify theme push --store app-development-test729.myshopify.com
