name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Check if Shopify API Password is set
        run: |
          if [ -z "${SHOPIFY_CLI_AUTH_TOKEN}" ]; then
            echo "SHOPIFY_CLI_AUTH_TOKEN is NOT set!"
          else
            echo "SHOPIFY_CLI_AUTH_TOKEN is set!"
          fi

      - name: Authenticate with Shopify CLI (Non-Interactive)
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_API_PASSWORD }}
        run: |
          echo "Authenticating with Shopify CLI..."
          shopify login --store app-development-test729.myshopify.com --password $SHOPIFY_CLI_AUTH_TOKEN

      - name: Deploy Theme
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_API_PASSWORD }}
        run: shopify theme push --store app-development-test729.myshopify.com
