name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Set environment variables
        run: |
          echo "SHOPIFY_PASSWORD=${{ secrets.SHOPIFY_PASSWORD }}" >> $GITHUB_ENV
          echo "SHOPIFY_STORE_URL=${{ secrets.SHOPIFY_STORE_URL }}" >> $GITHUB_ENV
          echo "SHOPIFY_THEME_ID=${{ secrets.SHOPIFY_THEME_ID }}" >> $GITHUB_ENV

      - name: Deploy Theme to Shopify
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          echo "Deploying Theme to Shopify..."
          shopify theme push --store "$SHOPIFY_STORE_URL" --password "$SHOPIFY_PASSWORD" --theme "$SHOPIFY_THEME_ID"
